### ISSUE TITLE
"composer create-project" gives an older version v1.0.5 when running with PHP 8.0.0

### ISSUE THREAD

**Issue by Hailong** [symfony/demo#1175]
As PHP 8.0.0 is around the corner, it will be interesting to try out Symfony on this new version of PHP.

While as the current PHP requirement in composer.json is "php: ^7.2.9", PHP 8 would not be able to get this latest version. Instead, it gets v1.0.5.

I also tried to create the demo project with v1.0.5, installation was fine but eventually Doctrine/ORM threw an error because of a bug in the old version. Error message is below:

```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/vagrant/pizza/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:2636
```

Creating the demo project with its latest version v1.6.3 works good with PHP 8.0.0, by appending `--ignore-platform-reqs` in the command:

```
composer create-project symfony/symfony-demo my_project --ignore-platform-reqs
```

**Comment by javiereguiluz** [comment]
Closing as probably fixed by #1185. Thanks!

**Comment by morrisonlevi** [comment]
This is not fixed; it tries to install an old version of symfony and dependencies.

```
$ php --version
PHP 8.0.2 (cli) (built: Feb  4 2021 18:01:33) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies
```

```
$ php composer.phar --version
Composer version 2.0.11 2021-02-24 14:57:23
```

```
$ php composer.phar create-project symfony/symfony-demo app
```

```
$ php ../composer.phar show "symfony/*"
symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.6 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.4.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.4.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.4.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.4.0 Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.4.0 Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.4.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.4.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.4.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.4.0 Symfony utilities for portability of PHP codes
symfony/swiftmailer-bundle v2.6.3 Symfony SwiftmailerBundle
symfony/symfony            v3.3.6 The Symfony PHP framework
```

-----

If I tell it to ignore platform reqs it installs a newer version:

```
$ php composer.phar  create-project --ignore-platform-reqs symfony/symfony-demo app
```

But when hitting `/en/blog/`:

> Compile Error: Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)

This issue seems related: https://github.com/symfony/symfony/issues/39582. Needs doctrine/dbal 2.12, I think?

```
php ../composer.phar why doctrine/dbal
dama/doctrine-test-bundle  v6.5.0  requires  doctrine/dbal (^2.9.3 || ^3.0)  
doctrine/doctrine-bundle   2.2.2   requires  doctrine/dbal (^2.9.0|^3.0)     
doctrine/migrations        3.0.2   requires  doctrine/dbal (^2.10)           
doctrine/orm               2.8.1   requires  doctrine/dbal (^2.10.0)
```

It seems `doctrine/orm` and `doctrine/migrations` are preventing it from using 2.12.
